### ISSUE TITLE
Migrate to full HTTPS

### ISSUE THREAD

**Issue by 0x010C** [ValentinBrclz/WP-EditCount-Bot#7]
The MediaWiki API will not allow HTTP usage any more very soon. It becomes urgent to migrate to HTTPS, otherwise the bot will stop working.

**Comment by ValentinBrclz** [comment]
Will do ASAP, thank you @0x010C :+1:

**Comment by ValentinBrclz** [comment]
Fixed in the config and deployed. Thx
